<?php
define('ROLE_ADMIN', 'admin');
define('ROLE_MODER', 'moderator');
define('ROLE_USER', 'user');

define('MAIL_TYPE_NEW_PROJECT', 'MAIL_API_KEY_NEW_PROJECT');
define('MAIL_TYPE_ADD_COMMENT', 'MAIL_API_KEY_ADD_COMMENT');
define('MAIL_TYPE_CONCURENT_ADD_OFFER', 'MAIL_API_KEY_CONCURENT_ADD_OFFER');